name: wf1

on:
  push:
    branches: [ main, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: |
          echo "I was executed"
          echo "${{ toJson(github) }}"