name: wf2

on:
  workflow_run:
    workflows: ["wf1"]
    branches: [ main ]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: |
          echo "I am validation workflow"