name: wf2

on:
  workflow_run:
    workflows: ['wf1']
    branches: [ main ]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run command
        run: |
          echo "I am validation workflow"
          echo ${{ github.event.head_commit.message }}
          echo ${{ toJson(github.event.workflow_run) }}
          echo ${{ toJson(github) }}
          echo ${{ toJson(job) }}